version: '3'
services:
  nginx:
    # 默认最新版本
    image: nginx:alpine
    # 容器名称
    container_name: test-nginx
    # 端口映射
    ports:
     - "84:80"
    # 数据卷
    volumes:
     # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
     - ./nginx/conf.d:/etc/nginx/conf.d
     # 映射配置文件
     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
     # 映射项目代码目录
     - /var/www/html/test/:/var/www/html
     # 映射系统时间
     - /etc/localtime:/etc/localtime
    links:
     - php:php
  php:
    # 镜像默认最新
    image: php:7.3-fpm-alpine
    # 容器名称
    container_name: test-php
    # 端口映射
    ports:
    #- "9501:9501"
    - "9507:9504"
    #- "9000:9999"
    # 数据卷
    volumes:
     - /var/www/html/test:/var/www/html
     - /etc/localtime:/etc/localtime
     - ./php/conf.d/php.ini:/usr/local/etc/php/php.ini:rw
    tty: true